[project]
name = "pdf-to-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.40.0",
    "ollama>=0.6.1",
    "pdfplumber>=0.11.8",
    "tyro>=1.0.3",
]
